version: "3.9"

services:
    rabbitmq:
        image: rabbitmq:3.12-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./dados:/var/lib/rabbitmq/
            - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
